-- 01_setup.sql
-- Creates the database objects and stage for the EBOC RAG Agent
-- Run this first, then upload PDFs to the stage via Snowsight

USE ROLE ACCOUNTADMIN;

-- Create schema (adjust database name as needed)
CREATE SCHEMA IF NOT EXISTS EXPLORER_SANDBOX.EBOC_RAG;

-- Grant permissions to the working role
GRANT USAGE ON DATABASE EXPLORER_SANDBOX TO ROLE SF_INTELLIGENCE_DEMO;
GRANT USAGE ON SCHEMA EXPLORER_SANDBOX.EBOC_RAG TO ROLE SF_INTELLIGENCE_DEMO;
GRANT ALL ON SCHEMA EXPLORER_SANDBOX.EBOC_RAG TO ROLE SF_INTELLIGENCE_DEMO;
GRANT CREATE STAGE ON SCHEMA EXPLORER_SANDBOX.EBOC_RAG TO ROLE SF_INTELLIGENCE_DEMO;
GRANT CREATE TABLE ON SCHEMA EXPLORER_SANDBOX.EBOC_RAG TO ROLE SF_INTELLIGENCE_DEMO;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA EXPLORER_SANDBOX.EBOC_RAG TO ROLE SF_INTELLIGENCE_DEMO;
GRANT CREATE AGENT ON SCHEMA EXPLORER_SANDBOX.EBOC_RAG TO ROLE SF_INTELLIGENCE_DEMO;
GRANT CREATE FILE FORMAT ON SCHEMA EXPLORER_SANDBOX.EBOC_RAG TO ROLE SF_INTELLIGENCE_DEMO;
GRANT CREATE TASK ON SCHEMA EXPLORER_SANDBOX.EBOC_RAG TO ROLE SF_INTELLIGENCE_DEMO;
GRANT CREATE DATASET ON SCHEMA EXPLORER_SANDBOX.EBOC_RAG TO ROLE SF_INTELLIGENCE_DEMO;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SF_INTELLIGENCE_DEMO;

-- Switch to working role
USE ROLE SF_INTELLIGENCE_DEMO;
USE WAREHOUSE APP_WH;

-- Create stage for PDF uploads
CREATE OR REPLACE STAGE EXPLORER_SANDBOX.EBOC_RAG.EBOC_PDFS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- After running this script:
-- 1. Navigate to EXPLORER_SANDBOX.EBOC_RAG.EBOC_PDFS in Snowsight
-- 2. Click "+ Files" and upload all EBOC guideline PDFs
-- 3. Run: ALTER STAGE EXPLORER_SANDBOX.EBOC_RAG.EBOC_PDFS REFRESH;
-- 4. Verify: SELECT COUNT(*) FROM DIRECTORY(@EXPLORER_SANDBOX.EBOC_RAG.EBOC_PDFS);
